# Klasifikasi Penyakti Glukoma dengan Algoritma KNN (K-Nearest Neighbor)

Program python berikut adalah program yang dibuat untuk memenuhi tugas mata kuliah pengolahan citra digital. Berikut adalah link dataset gambar https://www.kaggle.com/sshikamaru/glaucoma-detection. Gambar satu persatu di ekstraksi cirinya berdasarkan warna (RGB) lalu data hasil dari ekstraksi tersebut digunakan untuk membuat program klasifikasi dengan hasil seperti dibawah berikut :

**Pastikan file Data(CSV)Coba.csv sudah diupload pada runtime directori!**

1. Pemanggilan Library






In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

2. Mengimpor dataset yang telah diubah menjadi csv

In [ ]:
dataset = pd.read_csv('Data(CSV)Coba.csv')
#Mengambil fitur dari data
X = dataset.iloc[:, :-1].values
#Mengambil label (Output) dari data yang mana merupakan kolom terakhir pada csv
y = dataset.iloc[:, -1].values

3. Membagi dataset menjadi data training dan data testing

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
#Coba datanya ditampilkan
print(X_train)

[[122.14942614  70.8510677   26.69898017]
 [138.42876546  88.39588626  45.11291297]
 [112.19118627  69.31789557  30.43115664]
 [112.59987259  64.2639478   34.56357861]
 [117.37951342  65.53741328  43.13257504]
 [110.3372879   76.18566338  37.78205029]
 [108.42335876  60.72043212  20.85156012]
 [121.93441582  78.0594368   33.10719315]
 [114.7245067   68.00539716  23.27881829]
 [125.92907476  82.31070693  42.35307121]
 [139.69725529  85.98005644  58.16108481]
 [105.00406679  72.60466242  39.11527061]
 [106.54635445  71.56251891  44.8453153 ]
 [119.64282751  74.26531776  22.58877484]
 [106.01555443  77.56399107  41.56883828]
 [ 88.69840002  56.64843067  32.35141754]
 [157.42819722  95.27757645  41.77715969]
 [112.74775044  73.36079135  32.78107897]
 [157.01463318  94.9620773   41.2517484 ]
 [104.57616695  62.01393     25.7014459 ]
 [112.19943301  75.48552577  49.95616325]
 [115.339938    76.03571097  30.01558383]
 [125.13745975  74.65505775  29.63971535]
 [ 56.14353991  34.71458292  12.90

In [ ]:
print(y_train)

[0 0 1 1 0 0 0 0 0 1 0 1 1 1 0 1 0 1 0 1 1 1 1 0 0 0 0 1 1 0 1 1 1 0 1 1 1
 0 0 1 1 0 0 0]


In [ ]:
print(X_test)

[[115.93447955  78.23002434  42.6723005 ]
 [126.77745883  78.69810597  27.41141796]
 [124.30750895  76.27809397  17.80818065]
 [107.1930987   73.20837927  39.14631907]
 [106.23123709  72.8899107   39.21686125]
 [105.72339535  64.61355845  36.59877618]
 [141.1912144   90.3333772   39.96176386]
 [115.20204194  69.96487061  23.23696677]
 [ 93.43892193  58.7100838   39.50155926]
 [128.12419685  84.82455095  39.2255036 ]
 [133.26247168  75.61889919  25.51303434]
 [105.67717886  69.93604883  36.3292044 ]
 [116.92095645  66.07390706  23.1360871 ]
 [107.917123    61.43901014  15.50282907]
 [109.21414073  64.13976987  23.14375814]]


In [ ]:
print(y_test)

[1 0 0 1 1 1 0 0 0 1 1 1 0 0 0]


4. Mengubah data fitur menjadi data yang berada di suatu rentang skala

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#Melihat hasil perubahan
print(X_train)

[[ 1.86687058e-01 -2.80726466e-01 -6.59813929e-01]
 [ 1.09223738e+00  1.16465580e+00  1.02368651e+00]
 [-3.67247417e-01 -4.07032692e-01 -3.18598351e-01]
 [-3.44513938e-01 -8.23388464e-01  5.92098161e-02]
 [-7.86428732e-02 -7.18477467e-01  8.42633401e-01]
 [-4.70371888e-01  1.58749723e-01  3.53459749e-01]
 [-5.76835616e-01 -1.11531139e+00 -1.19441641e+00]
 [ 1.74726949e-01  3.13115461e-01 -7.39407491e-02]
 [-2.26329591e-01 -5.15159312e-01 -9.72503460e-01]
 [ 3.96932814e-01  6.63344815e-01  7.71366983e-01]
 [ 1.16279806e+00  9.65634218e-01  2.21662032e+00]
 [-7.67036267e-01 -1.36261324e-01  4.75349897e-01]
 [-6.81245372e-01 -2.22115489e-01  9.99221296e-01]
 [ 4.72556508e-02  5.47259835e-04 -1.03559093e+00]
 [-7.10771517e-01  2.72299509e-01  6.99668204e-01]
 [-1.67405107e+00 -1.45077218e+00 -1.43037806e-01]
 [ 2.14909485e+00  1.73158517e+00  7.18714064e-01]
 [-3.36288123e-01 -7.39696942e-02 -1.03755855e-01]
 [ 2.12609005e+00  1.70559363e+00  6.70678148e-01]
 [-7.90838512e-01 -1.00875008e+

In [ ]:
print(X_test)

[[-0.15902395  0.32716885  0.80055264]
 [ 0.44412481  0.36573049 -0.59467905]
 [ 0.30673201  0.16636437 -1.47265848]
 [-0.64526974 -0.08652575  0.47818851]
 [-0.69877401 -0.11276192  0.48463786]
 [-0.72702308 -0.79458674  0.24527849]
 [ 1.24590065  1.32427074  0.55274085]
 [-0.19976634 -0.35373341 -0.97632975]
 [-1.41035602 -1.28092848  0.51066648]
 [ 0.51903811  0.87044103  0.48542799]
 [ 0.80485845  0.11205839 -0.76823945]
 [-0.72959391 -0.35610781  0.22063279]
 [-0.10415044 -0.67427988 -0.98555271]
 [-0.60499536 -1.05611329 -1.68342608]
 [-0.53284778 -0.83361853 -0.98485138]]


5. Melatih model KNN dengan data training

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
#Parameter n_neighbors berisi tentang berapa banyak N tetangga yang ingin dibuat
classifier = KNeighborsClassifier(n_neighbors = 5, metric='minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

6. Mencoba memprediksi model dengan data trainingnya sendiri

In [ ]:
print(classifier.predict(sc.transform([[122.14942614,  70.8510677,   26.69898017]])))

[0]


7. Mencoba melihat hasil prediksi dengan menggunakan data test

In [ ]:
y_pred = classifier.predict(X_test)
#pada kolom kiri, menunjukkan hasil prediksi
#kolom kanan, menunjukkan hasil seharusnya
#Apabila sama antara kolom kiri dan kanan, maka hasil prediksi benar
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]]


8. Menghitung Akurasi dari Model

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Akurasi dari model adalah : ', accuracy_score(y_test, y_pred))

[[6 2]
 [1 6]]
Akurasi dari model adalah :  0.8
